# Auto-generated by scripts/generate_cli.py
# DO NOT EDIT MANUALLY

from __future__ import annotations

import json

import click


def _output(data: object) -> None:
    """Pretty-print response data as JSON."""
    click.echo(json.dumps(data, indent=2, default=str))


# ────────────────────────────────────────────────────────────────────
# Group: behaviors
# ────────────────────────────────────────────────────────────────────


@click.group("behaviors")
def behaviors_group() -> None:
    """View and manage behaviors."""
    pass


@behaviors_group.command("list")
@click.argument("project_id")
@click.option("--start-date", "start_date", default=None)
@click.option("--end-date", "end_date", default=None)
@click.pass_context
def behaviors_list(ctx, project_id, start_date, end_date):
    """List all behaviors in a project."""
    url = f"/projects/{project_id}/behaviors/"
    params = {}
    if start_date is not None:
        params["start_date"] = start_date
    if end_date is not None:
        params["end_date"] = end_date
    result = ctx.obj["client"].request("GET", url, params=params)
    _output(result)


@behaviors_group.command("get")
@click.argument("project_id")
@click.argument("behavior_id")
@click.option("--start-date", "start_date", default=None)
@click.option("--end-date", "end_date", default=None)
@click.pass_context
def behaviors_get(ctx, project_id, behavior_id, start_date, end_date):
    """Get behavior details."""
    url = f"/projects/{project_id}/behaviors/{behavior_id}"
    params = {}
    if start_date is not None:
        params["start_date"] = start_date
    if end_date is not None:
        params["end_date"] = end_date
    result = ctx.obj["client"].request("GET", url, params=params)
    _output(result)

# ────────────────────────────────────────────────────────────────────
# Group: datasets
# ────────────────────────────────────────────────────────────────────


@click.group("datasets")
def datasets_group() -> None:
    """Manage datasets."""
    pass


@datasets_group.command("list")
@click.argument("project_id")
@click.pass_context
def datasets_list(ctx, project_id):
    """List all datasets in a project."""
    url = f"/projects/{project_id}/datasets/"
    result = ctx.obj["client"].request("GET", url)
    _output(result)

# ────────────────────────────────────────────────────────────────────
# Group: judges
# ────────────────────────────────────────────────────────────────────


@click.group("judges")
def judges_group() -> None:
    """Manage judges (scorers)."""
    pass


@judges_group.command("list")
@click.argument("project_id")
@click.pass_context
def judges_list(ctx, project_id):
    """List all judges in a project."""
    url = f"/projects/{project_id}/judges/"
    result = ctx.obj["client"].request("GET", url)
    _output(result)


@judges_group.command("get")
@click.argument("project_id")
@click.argument("judge_id")
@click.pass_context
def judges_get(ctx, project_id, judge_id):
    """Get judge details and versions."""
    url = f"/projects/{project_id}/judges/{judge_id}"
    result = ctx.obj["client"].request("GET", url)
    _output(result)


@judges_group.command("models")
@click.argument("project_id")
@click.pass_context
def judges_models(ctx, project_id):
    """List available LLM models for judges."""
    url = f"/projects/{project_id}/judges/models"
    result = ctx.obj["client"].request("GET", url)
    _output(result)

# ────────────────────────────────────────────────────────────────────
# Group: orgs
# ────────────────────────────────────────────────────────────────────


@click.group("orgs")
def orgs_group() -> None:
    """Manage organizations."""
    pass


@orgs_group.command("list")
@click.pass_context
def orgs_list(ctx):
    """List organizations for the current user."""
    url = "/organizations/"
    result = ctx.obj["client"].request("GET", url)
    _output(result)


@orgs_group.command("get")
@click.argument("organization_id")
@click.pass_context
def orgs_get(ctx, organization_id):
    """Get organization details."""
    url = f"/organizations/{organization_id}"
    result = ctx.obj["client"].request("GET", url)
    _output(result)


@orgs_group.command("usage")
@click.argument("organization_id")
@click.pass_context
def orgs_usage(ctx, organization_id):
    """Get organization usage metrics."""
    url = f"/organizations/{organization_id}/usage"
    result = ctx.obj["client"].request("GET", url)
    _output(result)

# ────────────────────────────────────────────────────────────────────
# Group: projects
# ────────────────────────────────────────────────────────────────────


@click.group("projects")
def projects_group() -> None:
    """Manage projects."""
    pass


@projects_group.command("list")
@click.pass_context
def projects_list(ctx):
    """List all projects in the organization."""
    url = "/projects/"
    result = ctx.obj["client"].request("GET", url)
    _output(result)


@projects_group.command("get")
@click.argument("project_id")
@click.pass_context
def projects_get(ctx, project_id):
    """Get a project by ID."""
    url = f"/projects/{project_id}"
    result = ctx.obj["client"].request("GET", url)
    _output(result)

# ────────────────────────────────────────────────────────────────────
# Group: prompts
# ────────────────────────────────────────────────────────────────────


@click.group("prompts")
def prompts_group() -> None:
    """Manage prompt versions."""
    pass


@prompts_group.command("list")
@click.argument("project_id")
@click.pass_context
def prompts_list(ctx, project_id):
    """List all prompts in a project."""
    url = f"/projects/{project_id}/prompts/"
    result = ctx.obj["client"].request("GET", url)
    _output(result)


@prompts_group.command("get")
@click.argument("project_id")
@click.argument("prompt_name")
@click.pass_context
def prompts_get(ctx, project_id, prompt_name):
    """Get the latest version of a prompt."""
    url = f"/projects/{project_id}/prompts/{prompt_name}"
    result = ctx.obj["client"].request("GET", url)
    _output(result)


@prompts_group.command("versions")
@click.argument("project_id")
@click.argument("prompt_name")
@click.pass_context
def prompts_versions(ctx, project_id, prompt_name):
    """List all versions of a prompt."""
    url = f"/projects/{project_id}/prompts/{prompt_name}/list"
    result = ctx.obj["client"].request("GET", url)
    _output(result)

# ────────────────────────────────────────────────────────────────────
# Group: rules
# ────────────────────────────────────────────────────────────────────


@click.group("rules")
def rules_group() -> None:
    """Manage automation rules."""
    pass


@rules_group.command("list")
@click.argument("project_id")
@click.pass_context
def rules_list(ctx, project_id):
    """List all rules in a project."""
    url = f"/projects/{project_id}/rules/"
    result = ctx.obj["client"].request("GET", url)
    _output(result)

# ────────────────────────────────────────────────────────────────────
# Group: sessions
# ────────────────────────────────────────────────────────────────────


@click.group("sessions")
def sessions_group() -> None:
    """View and manage sessions."""
    pass


@sessions_group.command("get")
@click.argument("project_id")
@click.argument("session_id")
@click.pass_context
def sessions_get(ctx, project_id, session_id):
    """Get session details."""
    url = f"/projects/{project_id}/sessions/{session_id}"
    result = ctx.obj["client"].request("GET", url)
    _output(result)

# ────────────────────────────────────────────────────────────────────
# Group: tests
# ────────────────────────────────────────────────────────────────────


@click.group("tests")
def tests_group() -> None:
    """View test / experiment runs."""
    pass


@tests_group.command("list")
@click.argument("project_id")
@click.pass_context
def tests_list(ctx, project_id):
    """List test (experiment) runs."""
    url = f"/projects/{project_id}/tests/"
    result = ctx.obj["client"].request("GET", url)
    _output(result)

# ────────────────────────────────────────────────────────────────────
# Group: traces
# ────────────────────────────────────────────────────────────────────


@click.group("traces")
def traces_group() -> None:
    """View and manage traces."""
    pass


@traces_group.command("get")
@click.argument("project_id")
@click.argument("trace_id")
@click.pass_context
def traces_get(ctx, project_id, trace_id):
    """Get trace details."""
    url = f"/projects/{project_id}/traces/{trace_id}"
    result = ctx.obj["client"].request("GET", url)
    _output(result)


@traces_group.command("spans")
@click.argument("project_id")
@click.argument("trace_id")
@click.pass_context
def traces_spans(ctx, project_id, trace_id):
    """Get all spans for a trace."""
    url = f"/projects/{project_id}/traces/{trace_id}/spans"
    result = ctx.obj["client"].request("GET", url)
    _output(result)


@traces_group.command("behaviors")
@click.argument("project_id")
@click.argument("trace_id")
@click.pass_context
def traces_behaviors(ctx, project_id, trace_id):
    """Get behaviors detected on a trace."""
    url = f"/projects/{project_id}/traces/{trace_id}/behaviors"
    result = ctx.obj["client"].request("GET", url)
    _output(result)


def register_commands(cli: click.Group) -> None:
    """Register all generated command groups on the root CLI."""
    cli.add_command(behaviors_group, "behaviors")
    cli.add_command(datasets_group, "datasets")
    cli.add_command(judges_group, "judges")
    cli.add_command(orgs_group, "orgs")
    cli.add_command(projects_group, "projects")
    cli.add_command(prompts_group, "prompts")
    cli.add_command(rules_group, "rules")
    cli.add_command(sessions_group, "sessions")
    cli.add_command(tests_group, "tests")
    cli.add_command(traces_group, "traces")
