#!/usr/bin/env python3
"""Render the Homebrew formula for judgment-cli.

Usage:
    python scripts/generate_formula.py <version> <repo_root>

Resolves the CLI's runtime dependencies (and their transitive deps) by doing
a real ``pip install`` into a throwaway venv, then pulls each one's source
distribution metadata from PyPI to produce pinned ``resource`` blocks. The
``url`` / ``sha256`` for the CLI itself point at the GitHub Release source
tarball for the given version, so the package does not need to be on PyPI.

Writes the rendered Ruby formula to stdout.
"""

from __future__ import annotations

import hashlib
import json
import subprocess
import sys
import tempfile
import urllib.request
from pathlib import Path

REPO = "JudgmentLabs/cli"
PYTHON_DEP = "python@3.12"
EXCLUDE = {"judgment-cli", "pip", "setuptools", "wheel"}


def fetch_url(url: str) -> bytes:
    with urllib.request.urlopen(url) as r:
        return r.read()


def fetch_pypi_sdist(name: str, version: str) -> tuple[str, str]:
    """Return ``(sdist_url, sha256)`` for ``name==version`` from PyPI."""
    data = json.loads(
        fetch_url(f"https://pypi.org/pypi/{name}/{version}/json").decode()
    )
    for f in data["urls"]:
        if f["packagetype"] == "sdist":
            return f["url"], f["digests"]["sha256"]
    raise SystemExit(f"No sdist on PyPI for {name}=={version}")


def resolved_deps(repo_root: Path) -> list[tuple[str, str]]:
    """Resolve the full transitive runtime dep set via pip into a temp venv."""
    with tempfile.TemporaryDirectory() as tmp:
        venv = Path(tmp) / "venv"
        subprocess.check_call([sys.executable, "-m", "venv", str(venv)])
        pip = str(venv / "bin" / "pip")
        subprocess.check_call(
            [pip, "install", "--quiet", "--upgrade", "pip"]
        )
        subprocess.check_call(
            [pip, "install", "--quiet", str(repo_root)]
        )
        out = subprocess.check_output([pip, "list", "--format=json"])
    pkgs = json.loads(out)
    return sorted(
        (p["name"].lower(), p["version"])
        for p in pkgs
        if p["name"].lower() not in EXCLUDE
    )


def github_source(version: str) -> tuple[str, str]:
    url = f"https://github.com/{REPO}/archive/refs/tags/v{version}.tar.gz"
    return url, hashlib.sha256(fetch_url(url)).hexdigest()


def render(version: str, source_url: str, source_sha: str,
           resources: list[tuple[str, str, str]]) -> str:
    resource_blocks = "\n\n".join(
        f'  resource "{name}" do\n'
        f'    url "{url}"\n'
        f'    sha256 "{sha}"\n'
        f"  end"
        for name, url, sha in resources
    )

    return f"""\
# typed: strict
# frozen_string_literal: true

# This file is auto-generated by scripts/generate_formula.py in
# https://github.com/{REPO} on each release. DO NOT EDIT.
class JudgmentCli < Formula
  include Language::Python::Virtualenv

  desc "Command-line interface for the Judgment API"
  homepage "https://github.com/{REPO}"
  url "{source_url}"
  sha256 "{source_sha}"
  license "MIT"
  head "https://github.com/{REPO}.git", branch: "main"

  depends_on "{PYTHON_DEP}"

{resource_blocks}

  def install
    virtualenv_install_with_resources
    generate_completions_from_executable(bin/"judgment", "completion", shells: [:bash, :zsh, :fish])
  end

  test do
    assert_match version.to_s, shell_output("#{{bin}}/judgment --version")
  end
end
"""


def main() -> int:
    if len(sys.argv) != 3:
        print(
            "usage: generate_formula.py <version> <repo_root>", file=sys.stderr
        )
        return 1

    version = sys.argv[1].lstrip("v")
    repo_root = Path(sys.argv[2]).resolve()

    print(f"resolving deps from {repo_root} ...", file=sys.stderr)
    deps = resolved_deps(repo_root)

    print("fetching PyPI metadata ...", file=sys.stderr)
    resources = [
        (name, *fetch_pypi_sdist(name, dep_version))
        for name, dep_version in deps
    ]

    print(f"hashing source tarball for v{version} ...", file=sys.stderr)
    source_url, source_sha = github_source(version)

    sys.stdout.write(render(version, source_url, source_sha, resources))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
